[graph]
all-features = true

[advisories]
ignore = [
    # Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0134
    # rustls-pemfile v2.2.0
    "RUSTSEC-2025-0134",

    # Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0141
    # bincode v1.3.3
    "RUSTSEC-2025-0141",

    # Advisory: https://rustsec.org/advisories/RUSTSEC-2026-0009
    # time 0.3.41 registry+https://github.com/rust-lang/crates.io-index
    "RUSTSEC-2026-0009",
]
